try{
    let a;
    console.log(a.length);
    console.loh("HI there from inside");

}
catch(e){
    console.log("inside catch statement");
}
console.log("hi there");